# Version: 0.0.1
FROM ubuntu:14.04
MAINTAINER Avinash "avinashch237@gmail.com"
RUN apt-get update && apt-get install -y maven
RUN apt-get install -y git
RUN echo 'Hi, I am in your container' \
>/usr/share/html/index.html
EXPOSE 80